### ISSUE TITLE
Add validator dynamically

### ISSUE THREAD

**Issue by eigmax** [ieigen/ieigen#66]

**Comment by Weber-H2O2** [comment]
We can confirm that validators can be added dynamically.
A simple local deploy can confirm this:
  1. Clone the repo in two directories, e.g. (*arbitrum_1* and *arbitrum_2*), the pre-deploy instructions should be done in every directory
  2. Launch L1 in *arbitrum_1*, initial several validators using `yarn demo:initialize --validatorcount=N`, deploy with `yarn demo:deploy`
  3. Initial several validators in *arbitrum_2* using `yarn demo:initialize --validatorcount=M`, deploy with `yarn demo:deploy`

We can write a simple contract to validate that validators can be added dynamically. (Just see the logs they print)
